# directory for TMs
TMS_FILEPATH = "./src/tm_compatibility/"
# directory for tutors
TUTORS_FILEPATH = "./src/tutor_compatibility/"

# individual files for each TM or tutor
# the pokemon to add for each TM or tutor

DRAGONCLAW_FILE = "2 - Dragon Claw.txt"
DRAGONCLAW_POKEMON = "LAPRAS\nHUNTAIL\nTROPIUS\n"

CALMMIND_FILE = "4 - Calm Mind.txt"
CALMMIND_POKEMON = "EEVEE\nVAPOREON\nFLAREON\nJOLTEON\nUMBREON\nILLUMISE\nLEAFEON\nGLACEON\n"

TAUNT_FILE = "12 - Taunt.txt"
TAUNT_POKEMON = "PIDGEOT\nPACHIRISU\n"

ICEBEAM_FILE = "13 - Ice Beam.txt"
ICEBEAM_POKEMON = "RAIKOU\nSWALOT\n"

THUNDERBOLT_FILE = "24 - Thunderbolt.txt"
THUNDERBOLT_POKEMON = "TYPHLOSION\nSWALOT\n"

IRONHEAD_FILE = "26 - Iron Head.txt"
IRONHEAD_POKEMON = "HAXORUS\n"

FLAMETHROWER_FILE = "35 - Flamethower.txt"
FLAMETHROWER_POKEMON = "PARASECT\nBELLOSSOM\nSUNFLORA\nSWALOT\nCHERRIM"

FIREBLAST_FILE = "38 - Fire Blast.txt"
FIREBLAST_POKEMON = "PARASECT\nSUNFLORA\nBELLOSSOM\nSWALOT\nCHERRIM"

OUTRAGE_FILE = "44 - Outrage.txt"
OUTRAGE_POKEMON = "HUNTAIL\n"

EARTHPOWER_FILE = "48 - Earth Power.txt"
EARTHPOWER_POKEMON = "ARBOK\nTYPHLOSION\nENTEI\nMAGMORTAR\n"

GUNKSHOT_FILE = "49 - Gunk Shot.txt"
GUNKSHOT_POKEMON = "VICTREEBEL\nARIADOS\n"

ROOST_FILE = "51 - Roost.txt"
ROOST_POKEMON = "EMPOLEON\n"

HYPERVOICE_FILE = "52 - Hyper Voice.txt"
HYPERVOICE_POKEMON = "POLIWRATH\nGOLDUCK\nENTEI\nSWALOT\nTROPIUS\nMAGMORTAR\nSIMISAGE\nSIMISEAR\nSIMIPOUR\nARCHEOPS\n"

FOCUSBLAST_FILE = "52 - Focus Blast.txt"
FOCUSBLAST_POKEMON = "PIDGEOT\n"

ENERGYBALL_FILE = "53 - Energy Ball.txt"
ENERGYBALL_POKEMON = "VOLTORB\nELECTRODE\n"

SUPERPOWER_FILE = "53 - Superpower.txt"
SUPERPOWER_POKEMON = "LEDIAN\nELECTIVIRE\nZEBSTRIKA\n"

KNOCKOFF_FILE = "54 - Knock Off.txt"
KNOCKOFF_POKEMON = "DUSKNOIR\nVESPIQUEN\nBEWEAR\n"

DRAINPUNCH_FILE = "60 - Drain Punch.txt"
DRAINPUNCH_POKEMON = "THROH\n"

ROCKPOLISH_FILE = "69 - Rock Polish.txt"
ROCKPOLISH_POKEMON = "MAROWAK\nMAROWAK_A\n"

SPIKES_FILE = "73 - Spikes.txt"
SPIKES_POKEMON = "CLAYDOL\nBASTIODON\nPROBOPASS\nCARBINK\n"

TOXICSPIKES_FILE = "74 - Toxic Spikes.txt"
TOXICSPIKES_POKEMON = "KLEFKI\n"

SWORDSDANCE_FILE = "75 - Swords Dance.txt"
SWORDSDANCE_POKEMON = "GIRAFARIG\n"

DRAGONDANCE_FILE = "75 - Dragon Dance.txt"
DRAGONDANCE_POKEMON = "GARCHOMP\nMEGANIUM\nHUNTAIL\n"

NASTYPLOT_FILE = "77 - Nasty Plot.txt"
NASTYPLOT_POKEMON = "SCEPTILE\nSEVIPER\n"

DARKPULSE_FILE = "79 - Dark Pulse.txt"
DARKPULSE_POKEMON = "SCEPTILE\nVESPIQUEN\nMAGMORTAR\nUNFEZANT\nGOTHITELLE\nSEVIPER\n"

UTURN_FILE = "89 - U-Turn.txt"
UTURN_POKEMON = "AERODACTYL\n"

THUNDERFANG_FILE = "89 - Thunder Fang.txt"
THUNDERFANG_POKEMON = "FLOATZEL\n"

FIREFANG_FILE = "91 - Fire Fang.txt"
FIREFANG_POKEMON = "FLOATZEL\n"

HEAVYSLAM_FILE = "95 - Heavy Slam.txt"
HEAVYSLAM_POKEMON = "BLASTOISE\nHAXORUS\n"

DAZZLINGGLEAM_FILE = "102 - Dazzling Gleam.txt"
DAZZLINGGLEAM_POKEMON = "PERSIAN\nCHIMECHO\nLUVDISC\n"

AURASPHERE_FILE = "104 - Aura Sphere.txt"
AURASPHERE_POKEMON = "GOLDUCK\nGIRAFARIG\nESPEON\nUNFEZANT\nBEHEEYEM\n"

CRUNCH_FILE = "108 - Crunch.txt"
CRUNCH_POKEMON = "TAUROS\n"

PLAYROUGH_FILE = "115 - Play Rough.txt"
PLAYROUGH_POKEMON = "TAUROS\n"

PSYCHICFANGS_FILE = "118 - Psychic Fangs.txt"
PSYCHICFANGS_POKEMON = "ARCANINE\n"
